# Generated by Django 3.1.5 on 2021-01-19 22:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_auto_20210118_0441'),
        ('main_app', '0003_auto_20210119_1938'),
    ]

    operations = [
    ]
