# Generated by Django 3.1.5 on 2021-01-20 00:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0005_city_post'),
    ]

    operations = [
        migrations.AddField(
            model_name='city',
            name='city',
            field=models.CharField(default='', max_length=250),
        ),
        migrations.AddField(
            model_name='city',
            name='country',
            field=models.CharField(default='', max_length=250),
        ),
        migrations.AddField(
            model_name='city',
            name='image',
            field=models.URLField(default='', max_length=1000, verbose_name=''),
        ),
    ]
