# Generated by Django 2.2.12 on 2021-01-21 18:44

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0005_auto_20210120_1347'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='city',
            field=models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, to='main_app.City'),
        ),
        migrations.AddField(
            model_name='post',
            name='timestamp',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
